[package]
name = "bluetui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"]}
regex = "1.11.1"
tokio = { version = "1.43.0", features = ["full"] }
